version: '3'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  
  server:
    build: ./server
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/coschedule
      - JWT_SECRET=secret
    depends_on:
      - mongo
  
  client:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - server

volumes:
  mongo-data: